In [1]:
import pandas as pd
import numpy as np

In [2]:
hotel = pd.read_csv('../data/test.csv')
hotel

no_of_adults  no_of_children  no_of_weekend_nights  no_of_week_nights  \
0                3               0                     2                  3   
1                2               0                     0                  3   
2                2               0                     0                  2   
3                2               0                     2                  4   
4                2               0                     0                  2   
...            ...             ...                   ...                ...   
7250             2               0                     2                  3   
7251             2               0                     2                  0   
7252             2               0                     0                  2   
7253             1               0                     2                  0   
7254             2               0                     4                  6   

      type_of_meal_plan  required_car_parking_space  room_type_reserved  \
0                     1                           0                   4   
1                     1                           0                   1   
2                     2                           0                   1   
3                     1                           0                   4   
4                     2                           0                   1   
...                 ...                         ...                 ...   
7250                  1                           0                   4   
7251                  1                           0                   1   
7252                  1                           0                   1   
7253                  1                           0                   4   
7254                  0                           0                   1   

      lead_time  arrival_month  market_segment_type  repeated_guest  \
0            22              4                    1               0   
1           193             10                    0               0   
2           257              7                    0               0   
3             7              6                    1               0   
4            39              8                    0               0   
...         ...            ...                  ...             ...   
7250         88              9                    1               0   
7251         11              6                    1               0   
7252         52              2                    1               0   
7253         32             12                    1               0   
7254        293             12                    1               0   

      no_of_previous_cancellations  no_of_previous_bookings_not_canceled  \
0                                0                                     0   
1                                0                                     0   
2                                0                                     0   
3                                0                                     0   
4                                0                                     0   
...                            ...                                   ...   
7250                             0                                     0   
7251                             0                                     0   
7252                             0                                     0   
7253                             0                                     0   
7254                             0                                     0   

      avg_price_per_room  no_of_special_requests  booking_status  
0                 152.60                       2               0  
1                  65.00                       0               1  
2                 101.50                       0               1  
3                 156.00                       1               1  
4                 101.50                       0       

In [3]:
hotel['no_of_adults'].unique()

array([3, 2, 1, 0, 4], dtype=int64)

In [4]:
hotel['no_of_children'].unique()

array([ 0,  1,  2,  3, 10], dtype=int64)

In [5]:
hotel['no_of_weekend_nights'].unique()

array([2, 0, 1, 4, 5, 3, 6], dtype=int64)

In [6]:
hotel['no_of_week_nights'].unique()

array([ 3,  2,  4,  1,  5,  0,  6,  9,  7, 10, 11,  8, 13, 15, 12, 14, 16],
      dtype=int64)

In [7]:
hotel['type_of_meal_plan'].unique()

array([1, 2, 0], dtype=int64)

In [8]:
hotel['required_car_parking_space'].unique()

array([0, 1], dtype=int64)

In [9]:
hotel['room_type_reserved'].unique()

array([4, 1, 6, 5, 2, 7, 3], dtype=int64)

In [12]:
hotel['lead_time'].min()

0

In [13]:
hotel['arrival_month'].unique()

array([ 4, 10,  7,  6,  8,  1,  9, 11,  5, 12,  2,  3], dtype=int64)

In [14]:
hotel['market_segment_type'].unique()

array([1, 0, 2, 4, 3], dtype=int64)

In [15]:
hotel['repeated_guest'].unique()

array([0, 1], dtype=int64)

In [16]:
hotel['no_of_previous_cancellations'].unique()

array([ 0,  1, 11,  3,  5,  2], dtype=int64)

In [18]:
hotel['no_of_previous_bookings_not_canceled'].max()

55

In [22]:
hotel['avg_price_per_room'].max()

375.5

In [23]:
hotel['no_of_special_requests'].unique()

array([2, 0, 1, 4, 3, 5], dtype=int64)